name: Download and Check File

on:
  push:
    branches:
      - main

jobs:
  download-and-check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Set folder variable
        run: echo "FOLDER_NAME=my_folder" >> $GITHUB_ENV

      - name: Create directory and change directory
        run: |
          mkdir $FOLDER_NAME
          cd $FOLDER_NAME

      
      - name: Download File
        run: |
          FILE_URL="https://github.com/umeshaccion/swagger-check/swaggerWithExamplesV2.json"
          OUTPUT_PATH="$FOLDER_NAME/swaggerWithExamplesV2.json"
          
          curl -sSL $FILE_URL -o $OUTPUT_PATH
           current_directory=$(pwd)
            echo "Current working directory: $current_directory"
    

      - name: Check File and Directory
        run: |
          FILE_PATH="$FOLDER_NAME/swaggerWithExamplesV2.json"
          DIR_PATH="$FOLDER_NAME/"

          if [ -f "$FILE_PATH" ]; then
            echo "File exists: $FILE_PATH"
            cat $FILE_PATH
          else
            echo "File does not exist: $FILE_PATH"
            exit 1
          fi

          if [ -d "$DIR_PATH" ]; then
            echo "Directory exists: $DIR_PATH"
          else
            echo "Directory does not exist: $DIR_PATH"
            exit 1
          fi
